name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  repository_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build & Deploy
    steps:
      - uses: actions/checkout@v4
      - name: Publish
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: XODpYDcIyVtr2QNABoAQVxo-_FHT6jDvKddWoP4o
          accountId: 7ad006260c1ebc002135b9e031beba98
          command: deploy --env production --minify src/index.js
          environment: production
